#
# Makefile for IIO proximity sensors
#

# When adding new entries keep the list in alphabetical order

ccflags-y += -Werror
obj-$(CONFIG_NVS_IQS2X3)	+= nvs_iqs2x3.o
obj-$(CONFIG_CH201) += ch201/
obj-$(CONFIG_VL53L5CX) += vl53l5cx/
